spring.application.name=contabil

# DataSource em memória
spring.datasource.url=jdbc:h2:mem:contabil
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2

# Mostrar o SQL no console
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# Adia a execução do data.sql para depois que o Hibernate gerar as tabelas
spring.jpa.defer-datasource-initialization=true

# Criar ou atualizar o banco de dados automaticamente
spring.jpa.hibernate.ddl-auto=update

# Faz o Spring sempre executar o arquivo data.sql ao iniciar
spring.sql.init.mode=always